- name: demo on varibale
  hosts: all
  roles:
    - name: demo


- name: demo on varibale facts
  hosts: all
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "hostname = {{ansible_fqdn}}"