- name: demo on varibale
  hosts: all
  vars:
    URL: yahoo.com
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "URL = {{URL}}"

- name: demo on varibale facts
  hosts: all
  tasks:
    - name: print hello
      ansible.builtin.debug:
        msg: "hostname = {{ansible_fqdn}}"