- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: installed

- name:  remove old directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Download and Extract
  include_role:
    name: common
    tasks_from: download.yml

- name: copy the extracted frontend
  ansible.builtin.copy:
    src: /tmp/frontend-main/static/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: copy the configuration file
  ansible.builtin.copy:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    remote_src: no

- name: Restart Nginx service
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes