- name: Add Roboshop Apllictaion user
  ansible.builtin.user:
    name: roboshop

- name: Download from Github
  include_tasks:
    file: download-from-github.yml

-- name: Delete old app code
  file:
    path: /home/roboshop/{COMPONENT}
    state: absent

- name: copy the extracted {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop
