- name: Install Nodejs
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present


- name: Download from App code Github & App Add user
  include_tasks:
    file: download.yml

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Setup SystemD
  include_tasks:
    file: setup-systemd.yml