- name: Install Nodejs
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add Roboshop Apllictaion user
  ansible.builtin.user:
    name: roboshop

- name: Download from Github
  include_tasks:
    file: download.yml

- name: copy the extracted catalogue
  ansible.builtin.copy:
    src: /tmp/catalogue-main/
    dest: /home/roboshop/catalogue
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install Catalogue Dependencies
  community.general.npm:
    path: /home/roboshop/catalogue
    state: latest
  become_user: roboshop