- name: Install Nodejs
  ansible.builtin.yum:
    name: [ "nodejs", "make", "gcc-c++" ]
    state: present

- name: Add Roboshop Apllictaion user
  ansible.builtin.user:
    name: roboshop

- name: Download from Github
  include_tasks:
    file: download.yml

- name: copy the extracted {{COMPONENT}}
  ansible.builtin.copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop

- name: Install {{COMPONENT}} Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
    state: latest
  become_user: roboshop

- name: Update Systemd Configuration
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart {{COMPONENT}} service
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes